# Generated by Django 3.2.8 on 2021-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DFT', 'Draft'), ('SBMT', 'Submitted'), ('PBLH', 'Published'), ('RJT', 'Rejected')], default='DFT', max_length=4),
        ),
    ]
